# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Theobald Software HelpCenter
site_url: https://helpcenter.theobald-software.com/
#site_author: Valerie Schipka
site_description: >-
  The Theobald Software HelpCenters contains all documentation about our products.

# Repository
repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/helpcenter.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2024 Theobald Software GmbH <br><span style="color:#808080">“The best SAP interface is the one you don’t even notice.” - Patrick Theobald </span>
watch:
  - includes

# Configuration
theme:
  name: material
  custom_dir: overrides # overrides enable for announcements
  features:
     - content.tooltips # enables adding tooltips to links
     - navigation.expand # displays all pages in the navigation by default
     - navigation.indexes # adds landing pages for groups (index.md)
  palette:
    - scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png 

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi-cards.css 

# Plugins
plugins:
  - meta
  - typeset
  - awesome-pages
  - projects:
      projects_dir: projects
      #cache: false
      hoisting: false
      #projects_config_transform: !!python/name:projects.transform
  
# Continuous integration
  - group:
      enabled: !ENV CI
      plugins:
        #- optimize # compresses images and files
        - minify: # minifies HTML by stripping all whitespace from the generated documentation
            minify_html: true

# Additional configuration
extra:
  generator: false #footer display Made with Material for MkDocs
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/theobald-software/
      name: LinkedIn
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/TheobaldSoftware
      name: Youtube
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/theobaldsoftware/
      name: Instagram
    - icon: fontawesome/solid/envelope
      link: https://theobald-software.com/en/newsletter/
      name: Newsletter
   
# Extensions for Markdown Syntax  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 3
      #permalink: true
  - pymdownx.betterem: #improves bold/italic formatting (https://facelessuser.github.io/pymdown-extensions/extensions/betterem/)
      smart_enable: all
  - pymdownx.details #unfolding content, e.g., FAQs (https://facelessuser.github.io/pymdown-extensions/extensions/details/)
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #code highlighter (https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/)
  - pymdownx.keys #styling for keys, e.g., ++ctrl+alt+delete++ (https://facelessuser.github.io/pymdown-extensions/extensions/keys/)
  - pymdownx.smartsymbols
 # - pymdownx.snippets:
 #     base_path: includes
  - pymdownx.superfences
  - pymdownx.tabbed: #adds tabs (https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  
