# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Theobald Software Helpcenter
site_url: https://helpcenter.theobald-software.com/
#site_author: Valerie Schipka
#site_description: >-
#  Write your documentation in Markdown and create a professional static site in
#  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/helpcenter.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2024 Theobald Software GmbH <p style="color:#808080";>“The best SAP interface is the one you don’t even notice.” - Patrick Theobald</p>

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
     - content.tooltips
    # - header.autohide
    # - navigation.expand #displays all pages in the navigation
    # - navigation.footer
     - navigation.indexes #adds landing pages for groups
     - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.path #adds breadcrumbs
    # - navigation.prune
    # - navigation.sections #no groups in the navigation
     - navigation.tabs
     - navigation.tabs.sticky
    # - navigation.top #add a "back to top" button
    # - navigation.tracking #instantly adds the current headline to the URL
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate #adds the toc to the navigation
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png 

# Plugins
plugins:
  #- projects
      #projects_dir: projects
      #cache: false
      #hoisting: true
      #projects_config_transform: !!python/name:projects.transform
  #- pdf-export
  #     combined: false # specify if the whole documentation is exported (true) or if only the active page is exported (false)

# Continuous integration
#  - group:
 #     enabled: !ENV CI
#      plugins:
#         - optimize # compresses images and files
#        - minify: # minifies HTML by stripping all whitespace from the generated documentation
#            minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
    beta: Beta
  generator: false #footer display Made with Material for MkDocs
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSe8L5YDggZiVjgvBKfv-XCdbQAEJrseRh8MBh-jS92TU2aqzw/viewform?usp=pp_url&entry.853143515={url}" target=_blank>telling us what you're missing</a>.
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/theobald-software/
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/TheobaldSoftware
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/theobaldsoftware/
    - icon: fontawesome/solid/envelope
      link: https://theobald-software.com/en/newsletter/

      
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.betterem: #improves bold/italic formatting (https://facelessuser.github.io/pymdown-extensions/extensions/betterem/)
      smart_enable: all
  - pymdownx.details #unfolding content, e.g., FAQs (https://facelessuser.github.io/pymdown-extensions/extensions/details/)
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #code highlighter (https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/)
  - pymdownx.keys #styling for keys, e.g., ++ctrl+alt+delete++ (https://facelessuser.github.io/pymdown-extensions/extensions/keys/)
  - pymdownx.smartsymbols
 # - pymdownx.snippets:
 #     base_path: includes
  - pymdownx.superfences
  - pymdownx.tabbed: #adds tabs (https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      
nav:
  - ERPConnect: project://erpconnect