# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Theobald Software HelpCenter
site_url: https://helpcenter.theobald-software.com/
#site_author: Valerie Schipka
site_description: >-
  The Theobald Software HelpCenter contains user documentation and knowledge base article for the following products:
  Xtract Universal
  Xtract IS
  Xtract for Alteryx
  Board Connector
  ERPConnect
  yunIO
  Xtract Core

# Repository
repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/helpcenter.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2025 Theobald Software GmbH <br> <span style="color:#ED1A33"><a  style="color:#ED1A33" href="https://theobald-software.com/en/privacy-policy/" target="_blank" rel="noopener">privacy policy</a> - <a  style="color:#ED1A33" href="https://theobald-software.com/en/legal-notice" target="_blank" rel="noopener">legal notice</a> - <a style="color:#ED1A33" href="https://theobald-software.com/en/" target="_blank" rel="noopener">website</a></span>

watch:
  - includes

# Configuration
validation:
  links:
    not_found: ignore # ignores broken links (in the root directory) in the console
theme:
  name: material
  custom_dir: overrides # overrides enable for announcements
  icon:
    admonition:
      tip: material/lightbulb
      note: fontawesome/solid/circle-info
      api: material/web
  features:
     - content.code.copy # adds copy button in code blocks
     - navigation.expand # displays all pages in the navigation by default
     - navigation.indexes # adds landing pages for groups (index.md)
     - navigation.sections
     - toc.follow
     - navigation.tabs
  palette:
    - scheme: default
      primary: black
      accent: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png 

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi-cards.css 
  - assets/stylesheets/neoteroi-gantt.css 
  - assets/stylesheets/neoteroi-timeline.css 
  - assets/stylesheets/mkdocsoad.css 
  - assets/stylesheets/hyperscript.css
extra_javascript:
  - assets/javascripts/hyperscript.min.js
  - assets/javascripts/changelog.js
  - assets/javascripts/iconsearch_index.json
  - assets/javascripts/custom.129bd6ad.min.js
  - assets/javascripts/custom.129bd6ad.min.js.map
  
# Plugins
plugins:
  - meta
  - bpmn
  - typeset
  - awesome-pages
  - pagenav-generator
  - tags
  - search
  - mkdocs-pdf
  - render_swagger
  - redoc-tag
  - llmstxt:
      markdown_description: >-
        # User Documentation and Knowledge Base for Xtract IS
        Xtract IS is a powerful SAP plug-in for SQL Server Integration Services to extract mass data.
        Full: https://helpcenter.theobald-software.com/xtract-is/llms-full.txt

        # User Documentation and Knowledge Base for Xtract Universal
        Xtract Universal is a flexible SAP interface for databases, analytics, BI or cloud solutions.
        Full: https://helpcenter.theobald-software.com/xtract-universal/llms-full.txt

        # User Documentation Knowledge Base and Templates for Xtract for Alteryx
        Xtract for Alteryx integrates SAP data into Alteryx by offering a simple toolbox for the Alteryx Designer.
        Full: https://helpcenter.theobald-software.com/xtract-for-alteryx/llms-full.txt

        # User Documentation and Knowledge Base for Xtract Core
        Xtract Core is a web API server to extract SAP data and to write them to target environments using web calls. It can be used as a whitelabel solution.
        Full: https://helpcenter.theobald-software.com/xtract-core/llms-full.txt

        # User Documentation and Knowledge Base for Board Connector
        Board Connector makes SAP data available directly from Board, without an additional data warehouse. 
        Full: https://helpcenter.theobald-software.com/board-connector/llms-full.txt

        # HelpCenter with User Documentation and Knowledge Base for ERPConnect
        ERPConnect is a .NET programming library to develop SAP interfaces.
        Full: https://helpcenter.theobald-software.com/erpconnect/llms-full.txt

        # HelpCenter with User Documentation and Knowledge Base for yunIO
        yunIO is an SAP process automation tool for cloud environment that accesses SAP via web services.

      sections:
        Theobald Software Products:
         - index.md
  - swagger-ui-tag:
      supportedSubmitMethods: []
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - encryptcontent:
      esm: true
      hash_filenames:
        extensions:
          - 'json'
          - 'pdf'
        except:
            - 'CNAME'
            - 'iconsearch_index.json'
      #reload_scripts:
      #      - 'assets/javascripts/changelog.js'
      search_index: 'clear'
      html_template_path: "overrides/decrypt-form.tpl.html"
      password_inventory:
          classified: 'nCeRG50G5lkOTInSPcJ6'
      remember_password: True
      title_prefix: ''
      summary: 'Restricted Content' 
      decryption_failure_message: 'Wrong password.'
      encryption_info_message: 'You are about to access restricted content. Enter a valid password to continue.'
      #button_class: 'md-button'
      #password_button_text: 'ENTER'
      #password_button: True
  - privacy:
      links_attr_map:
        target: _blank # opens all external links in new tabs
  - projects:
      projects_dir: projects
      #cache: false
      hoisting: false
      #projects_config_transform: !!python/name:projects.transform
# Continuous integration
  - group:
      enabled: !ENV CI
      plugins:
        - minify: # minifies HTML by stripping all whitespace from the generated documentation
            minify_html: true


# Additional configuration
extra:
  generate_404: true  # Ensures static files are served
  generator: false #footer display Made with Material for MkDocs
  status:
    new: Recently added
    deprecated: Deprecated
    beta: Still in beta
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/theobald-software/
      name: LinkedIn
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/TheobaldSoftware
      name: Youtube
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/theobaldsoftware/
      name: Instagram
    - icon: fontawesome/solid/envelope
      link: https://theobald-software.com/en/newsletter/
      name: Newsletter
   
# Extensions for Markdown Syntax  
markdown_extensions:
  - neoteroi.projects
  - neoteroi.timeline
  - material.extensions.preview:
      targets:
        include:
          - draft-odata/*
  - pymdownx.critic
  - toc:
      separator: "-"
      title: On this Page
  - pymdownx.snippets:
      base_path: includes
  - pymdownx.superfences #for content tabs (version history)
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - tables
# notes, warnings, etc
  - admonition
  - pymdownx.details
# code blocks  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
# images & grids
  - attr_list
  - md_in_html
  - neoteroi.cards
# lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
# icons
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # breakless lists (for migration)
  - mdx_breakless_lists

