# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Theobald Software Helpcenter
site_url: https://helpcenter.theobald-software.com/
#site_author: Valerie Schipka
#site_description: >-
#  Write your documentation in Markdown and create a professional static site in
#  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/helpcenter.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2024 Theobald Software GmbH <p style="color:#808080";>“The best SAP interface is the one you don’t even notice.” - Patrick Theobald</p>

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
     - content.tooltips
    # - header.autohide
    # - navigation.expand #displays all pages in the navigation
    # - navigation.footer
     - navigation.indexes #adds landing pages for groups
     - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.path #adds breadcrumbs
    # - navigation.prune
    # - navigation.sections #no groups in the navigation
     - navigation.tabs
     - navigation.tabs.sticky
    # - navigation.top #add a "back to top" button
    # - navigation.tracking #instantly adds the current headline to the URL
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate #adds the toc to the navigation
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png 

# Plugins
plugins:

  - projects:
      projects_dir: projects
      cache: false
      hoisting: true
      #projects_config_transform: !!python/name:projects.transform
  #- pdf-export
  #     combined: false # specify if the whole documentation is exported (true) or if only the active page is exported (false)

# Continuous integration
#  - group:
 #     enabled: !ENV CI
#      plugins:
#         - optimize # compresses images and files
#        - minify: # minifies HTML by stripping all whitespace from the generated documentation
#            minify_html: true


nav:
  - ERPConnect: project://erpconnect