# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Theobald Software HelpCenter
site_url: https://helpcenter.theobald-software.com/
#site_author: Valerie Schipka
site_description: >-
  The Theobald Software HelpCenters contain all documentation about our products.

# Repository
repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/helpcenter.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2024 Theobald Software GmbH <br> <span style="color:#ED1A33"><a  style="color:#ED1A33" href="https://theobald-software.com/en/privacy-policy/" target="_blank" rel="noopener">privacy policy</a> - <a  style="color:#ED1A33" href="https://theobald-software.com/en/legal-notice" target="_blank" rel="noopener">legal notice</a> - <a style="color:#ED1A33" href="https://theobald-software.com/en/" target="_blank" rel="noopener">website</a></span>

watch:
  - includes

# Configuration
theme:
  name: material
  custom_dir: overrides # overrides enable for announcements
  icon:
    admonition:
      tip: material/lightbulb
      note: fontawesome/solid/circle-info
      api: material/web
  features:
     - content.code.copy # adds copy button in code blocks
     - navigation.expand # displays all pages in the navigation by default
     - navigation.indexes # adds landing pages for groups (index.md)
     - navigation.sections
     - navigation.tabs
  palette:
    - scheme: default
      primary: black
      accent: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png 

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi-cards.css 
  - assets/stylesheets/hyperscript.css
extra_javascript:
  - assets/javascripts/hyperscript.min.js
  - assets/javascripts/changelog.js
  - assets/javascripts/iconsearch_index.json
  - assets/javascripts/custom.129bd6ad.min.js
  - assets/javascripts/custom.129bd6ad.min.js.map
  
# Plugins
plugins:
  - meta
  - typeset
  - awesome-pages
  - pagenav-generator
  - tags
  - search
  - privacy:
      links_attr_map:
        target: _blank # opens all external links in new tabs
  - projects:
      projects_dir: projects
      #cache: false
      hoisting: false
      #projects_config_transform: !!python/name:projects.transform
# Continuous integration
  - group:
      enabled: !ENV CI
      plugins:
        #- optimize # compresses images and files
        - minify: # minifies HTML by stripping all whitespace from the generated documentation
            minify_html: true

# Additional configuration
extra:
  generator: false #footer display Made with Material for MkDocs
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/theobald-software/
      name: LinkedIn
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/TheobaldSoftware
      name: Youtube
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/theobaldsoftware/
      name: Instagram
    - icon: fontawesome/solid/envelope
      link: https://theobald-software.com/en/newsletter/
      name: Newsletter
   
# Extensions for Markdown Syntax  
markdown_extensions:
  - pymdownx.critic
  - toc:
      separator: "-"
      title: On this Page
  - pymdownx.snippets:
      base_path: includes
  - pymdownx.superfences #for content tabs (version history)
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - tables
# notes, warnings, etc
  - admonition
  - pymdownx.details
# code blocks  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
# images & grids
  - attr_list
  - md_in_html
  - neoteroi.cards
# lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
# icons
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # breakless lists (for migration)
  - mdx_breakless_lists

