# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Theobald Software Helpcenter
site_url: https://helpcenter.theobald-software.com/
#site_author: Valerie Schipka
#site_description: >-
#  Write your documentation in Markdown and create a professional static site in
#  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/helpcenter.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2024 Theobald Software GmbH <p style="color:#808080";>“The best SAP interface is the one you don’t even notice.” - Patrick Theobald</p>

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
     - content.tooltips # ebables adding tooltips to links
    # - header.autohide # hides the header when scrolling down
     - navigation.expand # displays all pages in the navigation by default
    # - navigation.footer
     - navigation.indexes # adds landing pages for groups (index.md)
    # - navigation.instant # load faster (no page reload for internal links)
    # - navigation.instant.prefetch # load faster (start loading content when hovering)
    # - navigation.instant.progress # enables a progress indicator 
    # - navigation.path # adds breadcrumbs
    # - navigation.prune # renders only HTML files of pages that are visible in the navigation
    # - navigation.sections # no groups in the navigation
     - navigation.tabs
     - navigation.tabs.sticky
    # - navigation.top # add a "back to top" button
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png 

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi-cards.css 
#extra_javascript:

# Plugins
plugins:
  - meta
  - typeset
  - awesome-pages
  - projects:
      projects_dir: projects
      cache: false
      hoisting: true
      #projects_config_transform: !!python/name:projects.transform
  
# Continuous integration
#  - group:
 #     enabled: !ENV CI
#      plugins:
#         - optimize # compresses images and files
#        - minify: # minifies HTML by stripping all whitespace from the generated documentation
#            minify_html: true

# Additional configuration
extra:
  generator: false #footer display Made with Material for MkDocs
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/theobald-software/
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/user/TheobaldSoftware
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/theobaldsoftware/
    - icon: fontawesome/solid/envelope
      link: https://theobald-software.com/en/newsletter/
   
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.betterem: #improves bold/italic formatting (https://facelessuser.github.io/pymdown-extensions/extensions/betterem/)
      smart_enable: all
  - pymdownx.details #unfolding content, e.g., FAQs (https://facelessuser.github.io/pymdown-extensions/extensions/details/)
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #code highlighter (https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/)
  - pymdownx.keys #styling for keys, e.g., ++ctrl+alt+delete++ (https://facelessuser.github.io/pymdown-extensions/extensions/keys/)
  - pymdownx.smartsymbols
 # - pymdownx.snippets:
 #     base_path: includes
  - pymdownx.superfences
  - pymdownx.tabbed: #adds tabs (https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  
