# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: ERPConnect Helpcenter
#site_url: http://erpconnect.theobald-software.com/
#site_author: Valerie Schipka
# site_description: >-
#  Write your documentation in Markdown and create a professional static site in
#  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
# repo_name: theobald-software/helpcenter.theobald-software.github.io
#repo_url: https://github.com/theobald-software/oh.theobald-software.github.io.git

# Copyright
copyright: Copyright &copy; 2024 Theobald Software GmbH #<br>“The best SAP interface is the one you don’t even notice.” - Patrick Theobald

# Configuration
theme:
  name: material
#  custom_dir: material/overrides
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
     - content.tooltips
    # - header.autohide
     - navigation.expand #displays all pages in the navigation
    # - navigation.footer
    # - navigation.indexes #adds landing pages for groups
     - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
     - navigation.path #adds breadcrumbs
    # - navigation.prune
    # - navigation.sections #no groups in the navigation
     - navigation.tabs
     - navigation.tabs.sticky
     - navigation.top #add a "back to top" button
     - navigation.tracking #instantly adds the current headline to the URL
     - search.highlight
     - search.share
     - search.suggest
    # - toc.follow
    # - toc.integrate #adds the toc to the navigation
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Poppins
    code: Roboto Mono
  favicon: assets/ERPConnect.png
  logo: assets/ERPConnect.png 

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css
  - stylesheets/neoteroi-cards.css 
  
# Plugins
plugins:
  - meta
  #- search:
  #    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - typeset
  #- git-revision-date-localized:
        #enable_creation_date: true
        #type: timeago
  #- macros:
  #    include_dir: ../../includes
  #- swagger-ui-tag
  #- glightbox #image zoom
  #- awesome-pages
  #- tags
  #- pdf-export:
  #     combined: false


  # Continuous integration
#  - group:
 #     enabled: !ENV CI
#      plugins:
#         - optimize
#        - minify:
#            minify_html: true


